fix: otlp docs cannot compile. (#507)
The bug was introduced when we started compiling grpc files using both tonic and grpcio.

The build logs says:
`thread 'main' panicked at 'Error generating protobuf: Os { code: 30, kind: Other, message: "Read-only file system" }`

But we already have compiled files in `proto/grpcio`. Thus we can ignore this error and print a warning message.